"""empty message

Revision ID: 022497197c7a
Revises: 
Create Date: 2024-03-06 23:26:49.758798

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '022497197c7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_keys',
    sa.Column('access_key_id', sa.String(length=16), nullable=False),
    sa.Column('secret_access_key', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('access_key_id')
    )
    op.create_table('tokens',
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('max_amount_day', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_table('access_keys_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('erc20_max_amount_day', sa.Integer(), nullable=False),
    sa.Column('native_max_amount_day', sa.Integer(), nullable=False),
    sa.Column('access_key_id', sa.String(), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['access_key_id'], ['access_keys.access_key_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hash', sa.String(length=32), nullable=False),
    sa.Column('recipient', sa.String(length=42), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('access_key_id', sa.String(), nullable=True),
    sa.Column('requester_ip', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['access_key_id'], ['access_keys.access_key_id'], ),
    sa.ForeignKeyConstraint(['token'], ['tokens.address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('access_keys_config')
    op.drop_table('tokens')
    op.drop_table('access_keys')
    # ### end Alembic commands ###
