"""empty message

Revision ID: 71441c34724e
Revises: 
Create Date: 2024-02-28 14:11:13.601403

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '71441c34724e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_keys',
    sa.Column('access_key_id', sa.String(length=16), nullable=False),
    sa.Column('secret_access_key', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('access_key_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_keys')
    # ### end Alembic commands ###
