"""empty message

Revision ID: b5d4ca37347c
Revises: 022497197c7a
Create Date: 2024-03-08 17:17:14.960915

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b5d4ca37347c'
down_revision = '022497197c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_keys', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['secret_access_key'])

    with op.batch_alter_table('access_keys_config', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['access_key_id', 'chain_id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('access_keys_config', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('access_keys', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
